
services:
  - type: web
    name: memechat
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
